docs(walkthrough): add place to binding thesis, create walkthrough on…
filkomers/walkthrough-yudisium pull request #4
Opened 2020-07-21 14:25 UTC by okzapradhana

2020-07-21 15:03 UTC, azzamsa commented
Hi.

Terima kasih atas kontribusinya.

menurut pendapat saya, bagaimana jika flowchart tersebut di convert menjadi xml/svg/png (dari draw.io) lalu di host di sini. Komentar dapat terpusat di issue repo ini, tidak berpencar-pencar.

Pro:
- lisensi diagram
- kontribusi diagram terpusat / berikut komentar atau pertanyaan.
- kelangsungan pemutakhiran diagram akan mudah jika berada di repo ini.

2020-07-22 01:00 UTC, okzapradhana commented
Ah i see, Okee mas sip sip saya coba dulu ya

2020-07-22 02:45 UTC, okzapradhana commented
@azzamsa seperti ini mas? cuman itu belum final karena belum kutambahin link-link reference terkait berkasnya. Kayaknya kutambah di markdown nanti

2020-07-23 00:37 UTC, azzamsa requested changes

2020-07-23 00:37 UTC, azzamsa commented on walkthrough-online.md
> +Flowchart ini akan dimaintain secara berkala. Jika sekiranya ada kekeliruan atau yang kurang dari step-stepnya, bisa langsung membuat issue atau komentar di whimsical.
belum di perbaharui ya?

2020-07-23 00:37 UTC, azzamsa commented on walkthrough-online.md
> +![daftar-yudisium-online](img/daftar-yudisium-online.png)
ini tambahkan xml nya juga (.drawio) di /img. Karena tidak mungkin kita contribute ke situ tanpa xml.

2020-07-23 00:37 UTC, azzamsa commented on walkthrough-online.md
> +Flowchart ini akan dimaintain secara berkala. Jika sekiranya ada kekeliruan atau yang kurang dari step-stepnya, bisa langsung membuat issue atau komentar di whimsical.
- maintain
- step

Mohon ganti dengan padanan yang benar ya.

2020-07-24 16:31 UTC, okzapradhana commented
sudah mas @azzamsa  diperbarui di latest commitnya, bisa dicek lagi. thankyou

2020-07-28 08:31 UTC, merged

2020-07-28 08:31 UTC, azzamsa commented
Terima kasih atas kontribusinya!